### ISSUE TITLE
RuntimeError: expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by moyan007** [rainofmine/Repulsion_Loss#10]
I met a trouble that 'RuntimeError: expected a non-empty list of Tensors'. Could anyone please help me with that?
Traceback (most recent call last):
  File "/home/Downloads/school/Repulsion_Loss/train.py", line 182, in <module>
    main()
  File "/home/Downloads/school/Repulsion_Loss/train.py", line 131, in main
    classification_loss, regression_loss, repgt_loss, repbox_loss = retinanet([data['img'].cuda().float(), data['annot'], data['ignore']])
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Downloads/school/Repulsion_Loss/model.py", line 264, in forward
    return self.focalLoss(classification, regression, anchors, annotations, ignores)
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Downloads/school/Repulsion_Loss/losses.py", line 242, in forward
    torch.stack(RepBox_losses).mean(dim=0, keepdim=True)
RuntimeError: expected a non-empty list of Tensors

**Comment by UrwLee** [comment]
I met the same problem,have u solved it?

**Comment by Lzhushuai** [comment]
I also met the same issues. I find it is because **RepBox_losses** is an empty List sometimes. I'm not sure what causes this situation.

 But I solve it by this way :

`if(len(Rep_Box_losses)>0):`

        return `orch.stack(classification_losses).mean(dim=0, keepdim=True), \

               torch.stack(regression_losses).mean(dim=0, keepdim=True), \

               torch.stack(RepGT_losses).mean(dim=0, keepdim=True), \

               torch.stack(RepBox_losses).mean(dim=0, keepdim=True) \
`else:`
       `return torch.stack(classification_losses).mean(dim=0, keepdim=True), \`

               torch.stack(regression_losses).mean(dim=0, keepdim=True), \

               torch.stack(RepGT_losses).mean(dim=0, keepdim=True), \

               `**torch.zeros([2]).cuda()**``
you should change `2 `to your `batch_size`.
